from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver
from selenium.webdriver.common.by import By
import webbrowser as wb
import pandas as pd
import time
import pjMachine
import pjScrap
from tkinter import messagebox
import sys

options = webdriver.ChromeOptions()
options.add_argument("headless")
driver = webdriver.Chrome(options=options)
driver.get('https://finance.daum.net/news#economy')
driver.implicitly_wait(50)
driver2 = webdriver.Chrome(options=options)
driver2.get('https://finance.daum.net/')
driver2.implicitly_wait(50)

news_link = []
news_title = []

news_title.append(driver.find_element(by=By.CLASS_NAME, value='tit').text)
news_link.append(driver.find_element(by=By.CLASS_NAME, value='tit').get_attribute('href'))
for i in range(1,3):
    for j in range(1,4):
        news_title.append(driver.find_element(by=By.XPATH, value='//*[@id="boxApp"]/div[1]/div[2]/ul['+str(i)+']/li['+str(j)+']/a').text)
        news_link.append(driver.find_element(by=By.XPATH, value='//*[@id="boxApp"]/div[1]/div[2]/ul['+str(i)+']/li['+str(j)+']/a').get_attribute('href'))


news = pd.DataFrame(data=news_link,index=news_title)

kospi = driver2.find_element(by=By.XPATH, value='//*[@id="boxIndexes"]/div[1]/span[1]/strong').text + " " + \
driver2.find_element(by=By.XPATH, value='//*[@id="boxIndexes"]/div[1]/span[1]/p[1]').text + " " + \
driver2.find_element(by=By.XPATH, value='//*[@id="boxIndexes"]/div[1]/span[1]/p[2]').text

kosdaq = driver2.find_element(by=By.XPATH, value='//*[@id="boxIndexes"]/div[2]/span[1]/strong').text + " " + \
driver2.find_element(by=By.XPATH, value='//*[@id="boxIndexes"]/div[2]/span[1]/p[1]').text + " " + \
driver2.find_element(by=By.XPATH, value='//*[@id="boxIndexes"]/div[2]/span[1]/p[2]').text

driver.close()
driver2.close()

today = time.strftime("%Y-%m-%d", time.localtime())

class Ui_pjSub(object):
    def CloseWindow(self):
        sys.exit()

    def stock_market_color(self):
        if '+' in kospi: self.kospi.setStyleSheet('color: red;')
        else: self.kospi.setStyleSheet('color: blue;')
        if '+' in kosdaq: self.kosdaq.setStyleSheet('color: red;')
        else: self.kosdaq.setStyleSheet('color: blue;')

    def selectstock(self):
        _translate = QtCore.QCoreApplication.translate
        Cop_Id = pjScrap.findCopId(self.select_stock.toPlainText())

        if Cop_Id is False :
            messagebox.showinfo("알림", "주식 검색 결과가 없습니다.")
        else :
            X_train, X_test, y_train, y_test, y_pred, closeStock, realStock, futureFrame10, futureFrame30, stockData30, todayClose, tomorrow_pred, realStock, r2 , stockData = pjMachine.learnData(Cop_Id)
            stockDf = stockData[['SK_DATE', 'SK_OPEN', 'SK_HIGH', 'SK_LOW', 'SK_CLOSE', 'SK_VOLUME']]
            stockDf.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']  # 열 이름 변경
            stockDf['Date'] = pd.to_datetime(stockDf['Date'])
            stockDf.set_index('Date', inplace=True)
            self.predicted_value.clear()

            for i, (date, value) in enumerate(zip(futureFrame10.index, futureFrame10.values)):
                __sortingEnabled = self.predicted_value.isSortingEnabled()
                item = QtWidgets.QTreeWidgetItem(self.predicted_value)
                item.setText(0, _translate("pjMain", date.strftime('%Y-%m-%d')))
                item.setText(1, _translate("pjMain", str(round(value[0], 2))))
                item.setText(2, _translate("pjMain", str(round(value[1], 2))))
                stockData30 = stockData30[::-1]

            self.yester_stock.setText("어제의 주식 : " + str(todayClose.values[0][0]))
            self.pre_today_stock.setText("전일비(예측값) : " + str(tomorrow_pred[0]))
            self.reslut_today_stock.setText("오늘의 주식 : " + str(realStock))
            self.result_stock.setText("정확도 : " + str(r2*100))

    def setupUi(self, pjMain):
        pjMain.setObjectName("pjMain")
        pjMain.setEnabled(True)
        pjMain.resize(981, 479)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pjMain.sizePolicy().hasHeightForWidth())
        pjMain.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Documents/last_real_pj/old_real_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pjMain.setWindowIcon(icon)
        pjMain.setStyleSheet("background-color:rgb(249,247,230);\n"
"selection-background-color:rgb(0, 0, 0);")
        pjMain.setProperty("pjMain", "")
        self.centralwidget = QtWidgets.QWidget(pjMain)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 140, 881, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(240,246,232);\n"
"selection-background-color:rgb(255,255,255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.select_stock = QtWidgets.QPlainTextEdit(self.frame)
        self.select_stock.setGeometry(QtCore.QRect(24, 40, 251, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.select_stock.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.select_stock.setFont(font)
        self.select_stock.setAcceptDrops(True)
        self.select_stock.setStyleSheet("background-color:rgb(255,255,255);\n"
"selection-background-color:rgb(255,255,255);\n"
"border-color:rgb(52,111,1);\n"
"border-style:solid;\n"
"border-width:0.5px;")
        self.select_stock.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.select_stock.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.select_stock.setObjectName("select_stock")
        self.search_button = QtWidgets.QToolButton(self.frame)
        self.search_button.setGeometry(QtCore.QRect(280, 40, 40, 25))
        self.search_button.clicked.connect(self.selectstock)


        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 110, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.search_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("background-color:rgb(32,110,17);\n"
"selection-background-color:rgb(255,255,255);\n"
"color:rgb(255,255,255);")
        self.search_button.setObjectName("search_button")
        self.news = QtWidgets.QListWidget(self.frame)
        self.news.setGeometry(QtCore.QRect(25, 69, 291, 171))
        self.news.setStyleSheet("background-color:rgb(255,255,255);\n"
"selection-background-color:rgb(255,255,255);\n"
"border-color:rgb(52,111,1);\n"
"border-style:solid;\n"
"border-width:0.5px;")
        self.news.setObjectName("news")
        item = QtWidgets.QListWidgetItem()
        self.news.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.news.addItem(item)
        self.predicted_value = QtWidgets.QTreeWidget(self.frame)
        self.predicted_value.setGeometry(QtCore.QRect(593, 50, 261, 191))
        self.predicted_value.setMinimumSize(QtCore.QSize(100, 30))
        self.predicted_value.setMaximumSize(QtCore.QSize(16777215, 231))
        self.predicted_value.setSizeIncrement(QtCore.QSize(0, 30))
        self.predicted_value.setBaseSize(QtCore.QSize(200, 30))
        self.predicted_value.setStyleSheet("border-color:rgb(0,0,0);\n"
"border-style:solid;\n"
"border-width:0.5px;\n"
"background-color:rgb(255,255,255);\n"
"selection-background-color:rgb(255,255,255);\n"
"height:35;")
        self.predicted_value.setLineWidth(100)
        self.predicted_value.setMidLineWidth(100)
        self.predicted_value.setAlternatingRowColors(True)
        self.predicted_value.setIconSize(QtCore.QSize(100, 30))
        self.predicted_value.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.predicted_value.setAutoExpandDelay(2)
        self.predicted_value.setIndentation(0)
        self.predicted_value.setUniformRowHeights(False)
        self.predicted_value.setAllColumnsShowFocus(True)
        self.predicted_value.setHeaderHidden(False)
        self.predicted_value.setExpandsOnDoubleClick(False)
        self.predicted_value.setColumnCount(3)
        self.predicted_value.setObjectName("predicted_value")
        self.predicted_value.headerItem().setText(0, "날짜")
        self.predicted_value.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.predicted_value.headerItem().setFont(0, font)
        self.predicted_value.headerItem().setBackground(0, QtGui.QColor(231, 225, 217))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.predicted_value.headerItem().setForeground(0, brush)
        self.predicted_value.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.predicted_value.headerItem().setFont(1, font)
        self.predicted_value.headerItem().setBackground(1, QtGui.QColor(231, 225, 217))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.predicted_value.headerItem().setForeground(1, brush)
        self.predicted_value.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.predicted_value.headerItem().setFont(2, font)
        self.predicted_value.headerItem().setBackground(2, QtGui.QColor(231, 225, 217))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.predicted_value.headerItem().setForeground(2, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.predicted_value)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(1, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(2, brush)
        self.predicted_value.header().setVisible(True)
        self.predicted_value.header().setCascadingSectionResizes(False)
        self.predicted_value.header().setDefaultSectionSize(75)
        self.predicted_value.header().setHighlightSections(False)
        self.predicted_value.header().setMinimumSectionSize(30)
        self.predicted_value.header().setStretchLastSection(False)
        self.yester_stock = QtWidgets.QLabel(self.frame)
        self.yester_stock.setGeometry(QtCore.QRect(340, 60, 230, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.yester_stock.setFont(font)
        self.yester_stock.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.yester_stock.setObjectName("yester_stock")
        self.pre_today_stock = QtWidgets.QLabel(self.frame)
        self.pre_today_stock.setGeometry(QtCore.QRect(340, 110, 230, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pre_today_stock.setFont(font)
        self.pre_today_stock.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.pre_today_stock.setObjectName("pre_today_stock")
        self.reslut_today_stock = QtWidgets.QLabel(self.frame)
        self.reslut_today_stock.setGeometry(QtCore.QRect(340, 160, 230, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.reslut_today_stock.setFont(font)
        self.reslut_today_stock.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.reslut_today_stock.setObjectName("reslut_today_stock")
        self.result_stock = QtWidgets.QLabel(self.frame)
        self.result_stock.setGeometry(QtCore.QRect(340, 210, 230, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.result_stock.setFont(font)
        self.result_stock.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.result_stock.setObjectName("result_stock")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(330, 50, 251, 191))
        self.frame_2.setStyleSheet("background-color:rgb(255,255,255);\n"
"selection-background-color:rgb(255,255,255);\n"
"border-color:rgb(52,111,1);\n"
"border-style:solid;\n"
"border-width:0.5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.now_data_2 = QtWidgets.QLabel(self.frame)
        self.now_data_2.setGeometry(QtCore.QRect(400, 5, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(20)
        self.now_data_2.setFont(font)
        self.now_data_2.setObjectName("now_data_2")
        self.now_data_3 = QtWidgets.QLabel(self.frame)
        self.now_data_3.setGeometry(QtCore.QRect(100, 5, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(20)
        self.now_data_3.setFont(font)
        self.now_data_3.setObjectName("now_data_3")
        self.now_data_4 = QtWidgets.QLabel(self.frame)
        self.now_data_4.setGeometry(QtCore.QRect(660, 5, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(20)
        self.now_data_4.setFont(font)
        self.now_data_4.setObjectName("now_data_4")
        self.CloseBtn = QtWidgets.QPushButton(self.frame)
        self.CloseBtn.setGeometry(QtCore.QRect(420, 250, 75, 23))
        self.CloseBtn.setObjectName("CloseBtn")
        self.CloseBtn.clicked.connect(self.CloseWindow)
        self.frame_2.raise_()
        self.select_stock.raise_()
        self.search_button.raise_()
        self.news.raise_()
        self.predicted_value.raise_()
        self.pre_today_stock.raise_()
        self.reslut_today_stock.raise_()
        self.result_stock.raise_()
        self.yester_stock.raise_()
        self.now_data_2.raise_()
        self.now_data_3.raise_()
        self.now_data_4.raise_()
        self.CloseBtn.raise_()
        self.stock_market = QtWidgets.QLabel(self.centralwidget)
        self.stock_market.setGeometry(QtCore.QRect(60, 30, 151, 51))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(15)
        self.stock_market.setFont(font)
        self.stock_market.setStyleSheet("background-image:url(:/Loginpage_logo.png)")
        self.stock_market.setText("")
        self.stock_market.setPixmap(QtGui.QPixmap("Loginpage_logo.png"))
        self.stock_market.setScaledContents(True)
        self.stock_market.setObjectName("stock_market")
        self.now_data = QtWidgets.QLabel(self.centralwidget)
        self.now_data.setGeometry(QtCore.QRect(60, 90, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(15)
        self.now_data.setFont(font)
        self.now_data.setObjectName("now_data")
        self.project_title = QtWidgets.QLabel(self.centralwidget)
        self.project_title.setGeometry(QtCore.QRect(400, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.project_title.setFont(font)
        self.project_title.setObjectName("project_title")
        self.kospi = QtWidgets.QLabel(self.centralwidget)
        self.kospi.setGeometry(QtCore.QRect(400, 65, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kospi.setFont(font)
        self.kospi.setObjectName("kospi")
        self.kosdaq = QtWidgets.QLabel(self.centralwidget)
        self.kosdaq.setGeometry(QtCore.QRect(400, 90, 360, 28))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR ExtraBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kosdaq.setFont(font)
        self.kosdaq.setObjectName("kosdaq")
        pjMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pjMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        pjMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pjMain)
        self.statusbar.setObjectName("statusbar")
        pjMain.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(pjMain)
        self.toolBar.setObjectName("toolBar")
        pjMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(pjMain)
        self.toolBar_2.setObjectName("toolBar_2")
        pjMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)

        self.retranslateUi(pjMain)
        QtCore.QMetaObject.connectSlotsByName(pjMain)

    def retranslateUi(self, pjMain):
        _translate = QtCore.QCoreApplication.translate
        pjMain.setWindowTitle(_translate("pjMain", "MainWindow"))
        self.search_button.setText(_translate("pjMain", "검색"))
        __sortingEnabled = self.news.isSortingEnabled()
        self.news.setSortingEnabled(False)
        self.news.clear()
        for i in range(len(news_title)):
            item = QtWidgets.QListWidgetItem()
            item.setText(news_title[i])
            self.news.addItem(item)
        self.news.setSortingEnabled(__sortingEnabled)
        self.news.itemDoubleClicked.connect(lambda: wb.open(news_link[self.news.currentRow()]))

        self.news.setSortingEnabled(__sortingEnabled)
        self.predicted_value.headerItem().setText(1, _translate("pjMain", "예측값"))
        self.predicted_value.headerItem().setText(2, _translate("pjMain", "전일비"))
        __sortingEnabled = self.predicted_value.isSortingEnabled()
        self.predicted_value.setSortingEnabled(False)
        self.predicted_value.setSortingEnabled(__sortingEnabled)
        self.yester_stock.setText(_translate("pjMain", "어제의주식"))
        self.pre_today_stock.setText(_translate("pjMain", "전일비(예측값)"))
        self.reslut_today_stock.setText(_translate("pjMain", "오늘의 주식"))
        self.result_stock.setText(_translate("pjMain", "정확도"))
        self.now_data_2.setText(_translate("pjMain", "국내 증시"))
        self.now_data_3.setText(_translate("pjMain", "예측 체결가"))
        self.now_data_4.setText(_translate("pjMain", "예측 체결가"))
        self.CloseBtn.setText(_translate("pjMain", "Close"))
        self.stock_market.setToolTip(_translate("pjMain", "<html><head/><body><p><br/></p></body></html>"))
        self.now_data.setText(_translate("pjMain", today))
        self.project_title.setText(_translate("pjMain", "오늘의 증시"))
        self.kospi.setText(_translate("pjMain", "코스피 : " + kospi))
        self.kosdaq.setText(_translate("pjMain", "코스닥 : " + kosdaq))
        self.toolBar.setWindowTitle(_translate("pjMain", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("pjMain", "toolBar_2"))
        self.stock_market_color()



